org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = com.ludwici.bbsf
archives_name = bbsf
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.16.10
fabric_api_version = 0.115.4+1.21.1
neoforge_version = 21.1.141