modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPLv3"

[[mods]]
modId = "bbsf"
version = "${version}"
displayName = "Better Block Sounds Fork"
authors = "ludwici"
description = '''
Block sounds, but better! (forked version)
'''
logoFile = "logo.png"

[[mixins]]
config = "bbsf.mixins.json"

[[dependencies.bbsf]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bbsf]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
